# General parameters
dataset: eye_movements
model_name: CatBoost # DecisionTree, KNN, SVM, DecisionTree, RandomForest, XGBoost, CatBoost, LightGBM,
    # ModelTree, TabNet, VIME, TabTransformer, RLN, DNFNet, STG, NAM, DeepFM, SAINT
objective: classification # Don't change
optimize_hyperparameters: True

# GPU parameters
use_gpu: True
# gpu_ids: [1]
data_parallel: True

# Optuna parameters - https://optuna.org/
n_trials: 36
direction: minimize

# Cross validation parameters
num_splits: 8
shuffle: True
seed: 42 # Don't change

# Preprocessing parameters
scale: False
target_encode: False

# Training parameters
batch_size: 128
val_batch_size: 128
early_stopping_rounds: 100
epochs: 1000
logging_period: 100

# About the data
num_classes: 3 # for classification
num_features: 27